fs-base/metadata/objects/Process_Instance__c.object
<CustomObject>
    <description>An instance of a process to display in the UI</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>Display name of process instance</description>
        <inlineHelpText>Display name of process instance</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Display order for this process instance</description>
        <inlineHelpText>Display order for this process instance</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Name of process that this process instance is a view on</description>
        <inlineHelpText>Name of process that this process instance is a view on</inlineHelpText>
        <label>Process</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Process Instance</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Process Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fs-base/metadata/classes/FSProcessRESTTest.cls
@isTest
public class FSProcessRESTTest {
    public static Process_Instance__c pi1;
	
    public class TestProcess implements FSProcess {
       	public void configure(FSProcessSettings sets) {
    	}
    	
    	public List<FSObjectMetadata> getObjectMetadata() {
    		return new List<FSObjectMetadata> {new FSObjectMetadata()};
    	}     	
    	
		public FSObjectDTO getObject(String objectType, Id objectId) {
			return null;			
		}

		public List<FSObjectDTO> getObjects(String objectType) {
			return null;			
		}
		
		public FSObjectDTO createObject(String objectType, FSObjectDTO obj) {
			return obj;
		}
		   	
		public FSObjectDTO updateObject(String objectType, Id objectId, FSObjectDTO obj) {
			return obj;
		}
		   	
		public void deleteObject(String objectType, Id objectId) {
		} 		  	
    }

	private static void setup() {
        pi1 = new Process_Instance__c(Label__c = 'test', Order__c = 0, Process__c = 'Test Process');
        insert pi1;		
        
        FSProcessRegister.register('Test Process', 'fsBase', 'FSProcessRESTTest.TestProcess', 'TBC', 'TBC', 'Test Component', new List<String> {'testobject'}, true);
        FSProcessRegister.saveRegistered();
	}
	
    static testMethod void testGetAllProcesses() {       
        setup();

        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.httpMethod = 'GET';
        RestContext.request.requestURI = '/' + FSNamespace.NAMESPACE + '/v1.0/fs/process';
        
        FSProcessREST.get();
        
        List<FSProcessDTO> result = (List<FSProcessDTO>) JSON.deserialize(RestContext.response.responseBody.toString(), List<FSProcessDTO>.class);
        
        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals(1, result.size());
        System.assertEquals(pi1.Id, result.get(0).id);
        System.assertEquals(pi1.Process__c, result.get(0).processName);
        System.assertEquals(pi1.Label__c, result.get(0).displayName);
        System.assertEquals('Test Component', result.get(0).componentName);
        
        System.assertEquals(1, result.get(0).objects.size());
    }
    
    static testMethod void testGetProcessById() {       
        setup();

        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.httpMethod = 'GET';
        RestContext.request.requestURI = '/' + FSNamespace.NAMESPACE + '/v1.0/fs/process/' +pi1.Id;
        
        FSProcessREST.get();
        
        FSProcessDTO result = (FSProcessDTO) JSON.deserialize(RestContext.response.responseBody.toString(), FSProcessDTO.class);
        
        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals(pi1.Id, result.id);
        System.assertEquals(pi1.Process__c, result.processName);
        System.assertEquals(pi1.Label__c, result.displayName);
        System.assertEquals('Test Component', result.componentName);
        
        System.assertEquals(1, result.objects.size());
    }
}