fs-base/metadata/objects/Process_Instance__c.object
<CustomObject>
    <description>An instance of a process to display in the UI</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if process instance is visible</description>
        <inlineHelpText>Indicates if process instance is visible</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <description>Key value pairs separated by newlines, used to configure the specific behaviour of the process</description>
        <inlineHelpText>Key value pairs separated by newlines, used to configure the specific behaviour of the process</inlineHelpText>
        <label>Additional Information</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date when this process instance should be hidden</description>
        <inlineHelpText>Date when this process instance should be hidden</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Display name of process instance</description>
        <inlineHelpText>Display name of process instance</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Display order for this process instance</description>
        <inlineHelpText>Display order for this process instance</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Name of process that this process instance is a view on</description>
        <inlineHelpText>Name of process that this process instance is a view on</inlineHelpText>
        <label>Process</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date when this process instance should be visible</description>
        <inlineHelpText>Date when this process instance should be visible</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Process Instance</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Process Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fs-base/metadata/classes/FSProcessInstanceController.cls
public with sharing class FSProcessInstanceController {
    public Process_Instance__c pi {get; set;}

    public final ApexPages.StandardController stdCtrl;

    public FSProcessInstanceController(ApexPages.StandardController stdCtrl) {
    
        this.pi = (Process_Instance__c)stdCtrl.getRecord();

        if (ApexPages.currentpage().getparameters().get('id') != null) {
        
            this.pi = [SELECT Active__c, CreatedById, CreatedDate, IsDeleted, End_Date__c, Label__c, LastModifiedById, LastModifiedDate, Order__c, OwnerId, Process__c, Name, Id, Start_Date__c, SystemModstamp, Additional_Information__c FROM Process_Instance__c WHERE Id = :ApexPages.currentpage().getparameters().get('id')];               
               
        } else {
			this.pi = new Process_Instance__c();           
        }       
    }

    public List<SelectOption> getProcessList() {        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--None--'));
                
        for (FSProcessRegister.RegisteredProcess proc : FSProcessRegister.getAllProcesses()) {
        	options.add(new SelectOption(proc.name, proc.name)); 
        }
        
        options.sort();
        return options;
    }
    
    public pageReference cancelMethod() {
        PageReference pageRef = new PageReference('/'+apexpages.currentpage().getparameters().get('id'));
        pageRef.setRedirect(true);
        return pageRef;                           
     }            
              
    public pageReference insertMethod() {
        if (this.pi.Process__c == '') {
            this.pi.Process__c = null;
        }
                        
        try {
        	upsert pi;        
        } catch(Exception e){
            ApexPages.addmessages(e);
            
            return null;
        }
        
        PageReference pageRef = new PageReference('/'+pi.Id);
        pageRef.setRedirect(true);
        return pageRef;            
	}     

    public Boolean getCheckProcess() {
        boolean msg;
        if(apexpages.currentpage().getparameters().get('id') != null) {
            msg = false;
        } else {
            msg = true;
        }
       
        return msg;
    }
}