fs-base/metadata/objects/Process_Instance__c.object
<CustomObject>
    <description>An instance of a process to display in the UI</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if process instance is visible</description>
        <inlineHelpText>Indicates if process instance is visible</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <description>Key value pairs separated by newlines, used to configure the specific behaviour of the process</description>
        <inlineHelpText>Key value pairs separated by newlines, used to configure the specific behaviour of the process</inlineHelpText>
        <label>Additional Information</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date when this process instance should be hidden</description>
        <inlineHelpText>Date when this process instance should be hidden</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Display name of process instance</description>
        <inlineHelpText>Display name of process instance</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Display order for this process instance</description>
        <inlineHelpText>Display order for this process instance</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Name of process that this process instance is a view on</description>
        <inlineHelpText>Name of process that this process instance is a view on</inlineHelpText>
        <label>Process</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date when this process instance should be visible</description>
        <inlineHelpText>Date when this process instance should be visible</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Process Instance</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Process Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fs-base/metadata/classes/FSProcessController.cls
public class FSProcessController {
    @AuraEnabled
    public static FSProcessDTO getProcess(Id processId, Map<String, String> params) {
		// lookup process details
		Process_Instance__c instance;
		try {
		    instance = [SELECT Id, Name, Label__c, Start_Date__c, End_Date__c, Active__c, Process__c, Order__c, Additional_Information__c FROM Process_Instance__c WHERE id = :processId AND Active__c = true AND (Start_Date__c = null OR Start_Date__c <= TODAY) AND (End_Date__c = null OR End_Date__c >= TODAY) LIMIT 1];		        				
		} catch (Exception ex) {
			System.debug(ex);
			System.debug(ex.getStackTraceString());
				
			throw new FSProcessInstanceException('Process instance not available');
		}
		        
		FSProcessRegister.RegisteredProcess regProc = FSProcessRegister.getProcess(instance.Process__c);
		if (regProc == null) {
		    throw new FSProcessInstanceException('Process instance has no corresponding process: ' + instance.Process__c);
		}
								
		// get the metadata associated wiht this process
		FSProcess proc = buildProcess(instance.Process__c, params);
			
		return FSProcessDTO.create(processId, instance.Process__c, instance.Label__c, regProc.componentName, proc.getObjectMetadata());
    }
    
    @AuraEnabled
    public static List<FSProcessDTO> getProcesses(Map<String, String> params) {
    	List<FSProcessDTO> dtos = new List<FSProcessDTO>();
    	
		for (Process_Instance__c instance : [SELECT Id, Name, Label__c, Start_Date__c, End_Date__c, Active__c, Process__c, Order__c, Additional_Information__c FROM Process_Instance__c WHERE Active__c = true AND (Start_Date__c = null OR Start_Date__c <= TODAY) AND (End_Date__c = null OR End_Date__c >= TODAY) ORDER BY Order__c DESC]) {
			try {			        
				FSProcessRegister.RegisteredProcess regProc = FSProcessRegister.getProcess(instance.Process__c);
				if (regProc == null) {
				    throw new FSProcessInstanceException('Process instance has no corresponding process: ' + instance.Process__c);
				}
				        
				// get the metadata associated wiht this process
				FSProcess proc = buildProcess(instance.Process__c, params);
						
				FSProcessDTO piDTO = FSProcessDTO.create(instance.Id, instance.Process__c, instance.Label__c, regProc.componentName, proc.getObjectMetadata());

				dtos.add(piDTO);
			} catch (Exception ex) {
				System.debug(ex);
				System.debug(ex.getStackTraceString());	
			}											
		}
				
		return dtos;
    }
    
	private static FSProcess buildProcess(String processName, Map<String, String> params) {
		if (processName == null) {
		    throw new FSObjectException('processName is null');
		}
				
			// lookup process
			FSProcessRegister.RegisteredProcess registeredProcess = FSProcessRegister.getProcess(processName);
				
			if (registeredProcess == null) {
		       	throw new FSProcessInstanceException('processName does not match a process: ' + processName); 
			}			
			
			// construct process class
			Type fsProcessType = Type.forName(registeredProcess.namespace, registeredProcess.className);        	
			
			FSProcess fsProcess = (FSProcess) fsProcessType.newInstance();
			
			FSProcessSettings settings = new FSProcessSettings();
						
			// add query params to the config
			settings.add(params);
			
			if (!settings.contains(FSProcessSettings.SUBJECT_USER_ID_KEY)) {
				settings.add(FSProcessSettings.SUBJECT_USER_ID_KEY, UserInfo.getUserId());
			}
			
			// configure the process
			fsProcess.configure(settings);
					
		return fsProcess;
	}   
}